<?php

add_action( 'wp_enqueue_scripts', 'tulostinkartta_enqueue_styles' );
	    function tulostinkartta_enqueue_styles() {
	    wp_enqueue_style( 'custom-community', get_template_directory_uri() . '/style.css' );
}

@ini_set( 'upload_max_size' , '64M' );
@ini_set( 'post_max_size', '64M');
@ini_set( 'max_execution_time', '300' );

/* Advanced Custom Forms fields for Tulostinkartta */

/*
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56c20e48aa2bf',
	'title' => 'Arvostelu',
	'fields' => array (
		array (
			'key' => 'field_56c218c5a9e02',
			'label' => 'Arvostelu',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c218e4a9e03',
			'label' => 'Arvostelun viesti',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c2198ca9e06',
						'operator' => '==',
						'value' => 'valmis',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Arvostele vastaanottamasi tulostustyö ja vapauta maksu?',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c218fda9e04',
			'label' => 'Arvostelu',
			'name' => 'arvostelunumero',
			'type' => 'number',
			'instructions' => 'Anna numeroarvostelu asteikolla 1-5.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c2198ca9e06',
						'operator' => '==',
						'value' => 'valmis',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 5,
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 5,
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c2193ba9e05',
			'label' => 'Kommentti',
			'name' => 'tekstiarvostelu',
			'type' => 'textarea',
			'instructions' => 'Kirjoita vapaavalintainen tekstiarvostelu?',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c2198ca9e06',
						'operator' => '==',
						'value' => 'valmis',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c22302ead71',
			'label' => 'Valmisviesti',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Kuittaa tulostustyö vastaanotetuksi?',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c2198ca9e06',
			'label' => 'Tila',
			'name' => 'tila',
			'type' => 'select',
			'instructions' => 'Oletko vastaanottanut tulostustyön?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'arvostelu' => 'Tulostustyö ei valmis',
				'valmis' => 'Tulostustyö on valmis',
				'peruutettu' => 'Tulostustyö peruutettu',
			),
			'default_value' => array (
				0 => 'arvostelu',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tulostuspyynto',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c20e375e628',
	'title' => 'Maksu',
	'fields' => array (
		array (
			'key' => 'field_56c217f57c521',
			'label' => 'Toimitus',
			'name' => 'toimitus',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c218027c522',
			'label' => 'Toimitusviesti',
			'name' => 'toimitusviesti',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Kuittaa että olet toimittanut tulostustyön sopimallanne tavalla.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c218257c523',
			'label' => 'Kommentti',
			'name' => 'maksu_kommentti',
			'type' => 'textarea',
			'instructions' => 'Voit kommentoida toimitusta?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c218457c524',
			'label' => 'Toimituksen tila',
			'name' => 'tila',
			'type' => 'select',
			'instructions' => 'Onko toimitus valmis?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'maksu' => 'Toimitus ei valmis',
				'arvostelu' => 'Toimitus valmis',
				'peruutettu' => 'Toimitus peruutettu',
			),
			'default_value' => array (
				0 => 0,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tulostuspyynto',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c08c7a0d1e0',
	'title' => 'Muokkaa omaa tulostintasi',
	'fields' => array (
		array (
			'key' => 'field_56880e1c57d0a',
			'label' => 'Tulostinsivu',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5688095f351e5',
			'label' => 'Otsikko',
			'name' => 'name',
			'type' => 'text',
			'instructions' => 'Tulostinsivun otsikko?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '3D-Tulostimeni',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56be850eb2054',
			'label' => 'Sijainti',
			'name' => 'sijainti',
			'type' => 'google_map',
			'instructions' => 'Tulostimen sijainti tulostinkartalla.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '60.8501746',
			'center_lng' => '24.4181247',
			'zoom' => 7,
			'height' => '',
		),
		array (
			'key' => 'field_56beadc2fa596',
			'label' => 'Tulostimen kuva',
			'name' => 'tulostimen_kuva',
			'type' => 'file',
			'instructions' => 'Tulostinsivun otsikkokuva?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'library' => 'uploadedTo',
			'return_format' => 'id',
			'min_size' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_56be83a759832',
			'label' => 'Kuvaus',
			'name' => 'kuvaus',
			'type' => 'wysiwyg',
			'instructions' => 'Kirjoita tulostimesi kuvaus.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 1,
			'tabs' => 'all',
		),
		array (
			'key' => 'field_56be8148b5535',
			'label' => 'Tulostin',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56be8179b5536',
			'label' => 'Tulostimen tekniset tiedot',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Tulostimen tekniset tiedot.',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_56c090d86e730',
			'label' => 'Tulostimet',
			'name' => 'tulostimet',
			'type' => 'repeater',
			'instructions' => 'Lisää tulostimesi!',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Lisää rivi',
			'sub_fields' => array (
				array (
					'key' => 'field_56c091026e731',
					'label' => 'Tulostimen malli',
					'name' => 'tulostimen_malli',
					'type' => 'text',
					'instructions' => 'Tulostimesi malli?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c091136e732',
					'label' => 'Tulostimesi leveys?',
					'name' => 'tulostimesi_leveys',
					'type' => 'number',
					'instructions' => 'Tulostimesi leveys mm?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c091306e733',
					'label' => 'Tulostimesi korkeus?',
					'name' => 'tulostimesi_korkeus',
					'type' => 'number',
					'instructions' => 'Tulostimesi korkeus mm?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c091486e734',
					'label' => 'Tulostimesi pituus',
					'name' => 'tulostimesi_pituus',
					'type' => 'number',
					'instructions' => 'Tulostimesi pituus mm.?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c091726e735',
					'label' => 'Tulostimesi hinta?',
					'name' => 'tulostimesi_hinta',
					'type' => 'number',
					'instructions' => 'Tulostustyön hinta tällä tulostimella per cm3?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0,01',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '0.01',
					'max' => 10,
					'step' => '0.01',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56c2b0270e40a',
			'label' => 'Toimitus',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c2b04c0e40b',
			'label' => 'Toimitusviesti',
			'name' => 'toimitusviesti',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Valitse käytössä olevat toimitus- ja maksutavat.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c2b5c02ee67',
			'label' => 'Maksutapa',
			'name' => 'maksutapa',
			'type' => 'checkbox',
			'instructions' => 'Onko käytössä Tulostinkartan Bitcoin Escrow -maksukäytävä vai hoidatteko laskutuksen itse, esimerkiksi käteinen noudon yhteydessä?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'bitcoin' => 'Bitcoin',
				'muu' => 'Muu',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		array (
			'key' => 'field_56c2b5942ee66',
			'label' => 'Toimitustapa',
			'name' => 'toimitustapa',
			'type' => 'checkbox',
			'instructions' => 'Noudetaanko tulostettavat työt vai postitatteko ne?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'posti' => 'Posti',
				'nouto' => 'Nouto',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		array (
			'key' => 'field_56880e4719c3a',
			'label' => 'Filamentit',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56be820480b63',
			'label' => 'Filamenttien tiedot',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Lisää käytettävissä olevat filamentit ja niiden hinnat!',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_56c08df3bd95a',
			'label' => 'Filamentit',
			'name' => 'filamentit_lista',
			'type' => 'repeater',
			'instructions' => 'Lisää tähän vähintään yksi filamentti!',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Lisää rivi',
			'sub_fields' => array (
				array (
					'key' => 'field_56c08e13bd95b',
					'label' => 'Filamentin nimi',
					'name' => 'filamentin_nimi',
					'type' => 'text',
					'instructions' => 'Filamenttisi nimi?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c08e27bd95c',
					'label' => 'Filamenttisi hinta?',
					'name' => 'filamenttisi_hinta',
					'type' => 'number',
					'instructions' => 'Filamentin hinta euroissa per kuutiosentti?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0,03',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '0.01',
					'max' => 10,
					'step' => '0.01',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c08e76bd95d',
					'label' => 'Filamentin väri',
					'name' => 'filamentin_vari',
					'type' => 'color_picker',
					'instructions' => 'Filamenttisi väri?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
			),
		),
		array (
			'key' => 'field_56be832e98dc0',
			'label' => 'Julkaisu',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56be834298dc1',
			'label' => 'Julkaise tulostin?',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Täällä voit julkaista tulostimesi tulostinkartalla tai piilottaa sen.',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_56be82c520768',
			'label' => 'Julkaise',
			'name' => 'julkaise',
			'type' => 'select',
			'instructions' => 'Onko tulostimesi julkinen vai piilossa?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'draft' => 'Piilossa',
				'publish' => 'Julkaise',
			),
			'default_value' => array (
				0 => 0,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tulostin',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c20e1473255',
	'title' => 'Tarjous',
	'fields' => array (
		array (
			'key' => 'field_56c21098d584b',
			'label' => 'Tulostus',
			'name' => 'tulostus',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c210abd584c',
			'label' => 'Tulostustyön tiedot',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Tarjouksen tulostustyön tiedot.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c2100abb8ef',
			'label' => 'Tiedosto',
			'name' => 'tiedosto',
			'type' => 'text',
			'instructions' => 'Tulostettava tiedosto',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c21072e4551',
			'label' => 'Määrä',
			'name' => 'maara',
			'type' => 'number',
			'instructions' => 'Tulostettava määrä.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c20fafbb8ec',
			'label' => 'Tulostinmalli',
			'name' => 'tulostinmalli',
			'type' => 'text',
			'instructions' => 'Käytetty tulostin',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c20f98bb8eb',
			'label' => 'Materiaali',
			'name' => 'materiaali',
			'type' => 'text',
			'instructions' => 'Käytetty filamentti',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c20fc2bb8ed',
			'label' => 'Kappalehinta',
			'name' => 'hinta',
			'type' => 'number',
			'instructions' => 'Kappalehinta.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '€',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c20febbb8ee',
			'label' => 'Kokonaishinta',
			'name' => 'tarjous',
			'type' => 'number',
			'instructions' => 'Kokonaishinta.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '€',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c210f1efa81',
			'label' => 'Toimitus',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c21106efa82',
			'label' => 'Toimituksen tiedot',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Anna tähän tiedot laskutuksesta ja toimituksesta.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c21130efa83',
			'label' => 'Toimitustapa',
			'name' => 'toimitustapa',
			'type' => 'textarea',
			'instructions' => 'Toimitatko työn postissa vai onko se noudettavissa luotasi? ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c21186efa84',
			'label' => 'Maksutapa',
			'name' => 'maksutapa',
			'type' => 'textarea',
			'instructions' => 'Kerro miten laskutat toimitustyön ja anna maksuun tarvittavat tiedot?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c21237f439e',
			'label' => 'Lähetä tarjous',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c21247f439f',
			'label' => 'Lähetysviesti',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Lähetä tarjous tai peruuta se!',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c212d9f41df',
			'label' => 'Kommentti',
			'name' => 'tarjous_kommentti',
			'type' => 'textarea',
			'instructions' => 'Voit kommentoida tarjousta tai kertoa miksi olet peruuttanut sen?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c21282f43a0',
			'label' => 'Lähetä tarjous?',
			'name' => 'tila',
			'type' => 'select',
			'instructions' => 'Lähetä tai peruuta tarjous?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'tarjous' => 'Luonnos',
				'tilaus' => 'Lähetä tarjous',
				'peruutettu' => 'Peruuta tarjous',
			),
			'default_value' => array (
				0 => 'tarjous',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tulostuspyynto',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56c20e26a2cae',
	'title' => 'Tilaus',
	'fields' => array (
		array (
			'key' => 'field_56c213c5e0f0c',
			'label' => 'Tilaus',
			'name' => 'tilaus',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c213d3e0f0d',
			'label' => 'Tilausviesti',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Anna tilauksesi tiedot.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56c2175040616',
			'label' => 'Tilauksen kommentti',
			'name' => 'tilauksen_kommentti',
			'type' => 'textarea',
			'instructions' => 'Voit kommentoida tilausta.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c2171440615',
			'label' => 'Lähetä tilaus',
			'name' => 'tila',
			'type' => 'select',
			'instructions' => 'Lähetä tilaus tai peruuta se?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'tilaus' => 'Luonnos',
				'maksu' => 'Lähetä tilaus',
				'peruutettu' => 'Peruuta tilaus',
			),
			'default_value' => array (
				0 => 'tilaus',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tulostuspyynto',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
*/
?>